version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_postgresql_value:/var/lib/postgresql/data/
    env_file:
      - ../src/.env

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ../src/.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend


volumes:
  db_postgresql_value:
